# Generated by Django 3.2.9 on 2021-11-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=750, null=True)),
                ('url', models.URLField(blank=True)),
                ('code_url', models.URLField(blank=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
