# Generated by Django 3.2.6 on 2021-08-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=240)),
                ('url', models.URLField(blank=True)),
                ('code_url', models.URLField(blank=True)),
            ],
        ),
    ]
