# Generated by Django 3.2.9 on 2021-11-02 11:18

from django.db import migrations, models
import portfolioproject.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(storage=portfolioproject.storage_backends.MediaStorage, upload_to=''),
        ),
    ]
