# Generated by Django 3.2.6 on 2021-08-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='static/portfolioapp/images'),
        ),
    ]
